In [1]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    m = mode
    s = shape
    if m == 'zeros': 
     return np.zeros(s)
     
    elif m == 'ones':
        return np.ones(s)
    elif m == 'full':
        if value is None:
            raise ValueError("Value cannot be None")
        return np.full(s, value)
    elif m == 'identity':
        if not isinstance(shape, int):
            raise ValueError("Shape must be an integer for identity matrix.")
        return np.identity(shape)
    else:
        raise ValueError("Unsupported mode. Use 'zeros', 'ones', 'full', or 'identity'.")


In [2]:
print(array_factory('zeros', (2,3)))
print(array_factory('ones', (3,3)))
print(array_factory('full', (2,2), value=7))
print(array_factory('identity', 4))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Rule: Change the shape of arr1 to new_shape
        reshaped_arr1 = arr1.reshape(new_shape)

        # Rule: Vertical Stacking (vstack)
        # Requirement: Both matrices must have the same number of columns
        if reshaped_arr1.shape[1] != arr2.shape[1]:
            raise ValueError(
                f"Column mismatch: reshaped_arr1 has {reshaped_arr1.shape[1]} columns, "
                f"but arr2 has {arr2.shape[1]} columns."
            )

        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")


In [4]:
data1 = [1,2,3,4,5,6]
data2 = [[7,8,9],[10,11,12]]

print(secure_reshape_and_stack(data1, data2, (2,3)))



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
