In [1]:
import numpy as np


In [5]:
lst = [1,2,3,4]
print(lst)
print(type(lst))
print("="*30)
s = np.array(5)
print(s)
print(s.ndim)
print(s.shape)
print("="*30)
 
v = np.array([1,2,3,4])
print(v)
print(v.ndim)
print(v.shape)
print("="*30)
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m)
print(m.ndim)
print(m.shape)

[1, 2, 3, 4]
<class 'list'>
5
0
()
[1 2 3 4]
1
(4,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [7]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
vec = np.array([1,2,3,4])
#mat = vec.reshape(vec.shape[0],1)  #first method
mat = vec[:,None]       #second method
mat


array([[1],
       [2],
       [3],
       [4]])

In [10]:
def array_reshape(arr, rows, cols):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except(TypeError, ValueError) as e:
        raise ValueError(f"Invaled reshape operation: {e}")

In [13]:
vec = [1,2,3,4,5,6]
array_reshape(vec, 2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
mat = np.array([[1.1,'2',3],
               [4,5,6],
               [7,8,9]])
print(mat.dtype)
print(mat)


<U32
[['1.1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [21]:
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
fmat = mat.astype(float)
print(fmat.dtype)
print(fmat)

float64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [22]:
def convert_dtype(arr, dtype):
    try:
        arr = np.array(arr)
        return arr.astype(dtype)
    except TypeError as e:
        raise TypeError(f"invalid target data type: {dtype}") from e

In [ ]:
v = np.array([1,2,3,5,1])
v[3]

mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [3,2,6]])
mat[1,2]
mat[1:3, 0:2]   #gets the values between rows 1 to 2, and columns 0 to 1 
mat.T   #transforms the matrix, rows becomes columns

array([[4, 5],
       [7, 8]])

In [30]:
mat = np.zeros((3,4))
mat
mat1 = np.ones((3,4))
mat1

mat3 = np.full((3,4),6)
mat3

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [32]:
def init_arr(shape, value = 0):
    return np.full(shape, value)


In [35]:
zeros = init_arr((3,4),5)
zeros

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])